### ISSUE TITLE
isLikedBy Issues

### ISSUE THREAD

**Issue by rpeterson** [copleykj/socialize-likeable#2]
I will assume this is my issue, but when I have a collection that I have extended from LikableModel, I can like it fine, but when I call isLikedBy(Meteor.user()) on the item it always returns false. Any ideas on this?

**Comment by copleykj** [comment]
This is just an issue of unpublished data. To use this you'll need to publish the likes for the model that belong to the user.

**Comment by rpeterson** [comment]
Ahh, okay. Makes sense. Didn't think about it not being published.

**Comment by limingth** [comment]
I also encountered this problem. I also thought that package should publish the likes itself.

**Comment by copleykj** [comment]
The issue with this is that a like can be linked to any number of
collections. The likes would have to be published for the records they
relate to when those records are published and there is no way of knowing
which collections you have made likeable. For packages such as
`socialize:feed` that use this package, yes I could publish the likes in
that case. I however am going to be removing the publications in all
socialize packages so that you aren't locked in to any one package for
joins.
